let tab="";
objectData.map((value)=>{
  tab+=`
  <div class="container">
  <div class="table">
<table style="width:100%">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>BranchType</th>
    <th>DeliveryStatus</th>
    <th>Circle</th>
    <th>District</th>
    <th>Division</th>
    <th>Region</th>
    <th>Block</th>
    <th>State</th>
    <th>Country</th>
    <th>Pincode</th>
  </tr>
  <tr>
    <td>${value.PostOffice[0].Name}</td>
    <td>${value.PostOffice[0].Description}</td>
    <td>${value.PostOffice[0].BranchType}</td>
    <td>${value.PostOffice[0].DeliveryStatus}</td>
    <td>${value.PostOffice[0].Circle}</td>
    <td>${value.PostOffice[0].District}</td>
    <td>${value.PostOffice[0].Division}</td>
    <td>${value.PostOffice[0].Region}</td>
    <td>${value.PostOffice[0].Block}</td>
    <td>${value.PostOffice[0].State}</td>
    <td>${value.PostOffice[0].Country}</td>
    <td>${value.PostOffice[0].Pincode}</td>
  </tr>
  <tr>
    <td>${value.PostOffice[1].Name}</td>
    <td>${value.PostOffice[1].Description}</td>
    <td>${value.PostOffice[1].BranchType}</td>
    <td>${value.PostOffice[1].DeliveryStatus}</td>
    <td>${value.PostOffice[1].Circle}</td>
    <td>${value.PostOffice[1].District}</td>
    <td>${value.PostOffice[1].Division}</td>
    <td>${value.PostOffice[1].Region}</td>
    <td>${value.PostOffice[1].Block}</td>
    <td>${value.PostOffice[1].State}</td>
    <td>${value.PostOffice[1].Country}</td>
    <td>${value.PostOffice[1].Pincode}</td>
  </tr>
  <tr>
    <td>${value.PostOffice[2].Name}</td>
    <td>${value.PostOffice[2].Description}</td>
    <td>${value.PostOffice[2].BranchType}</td>
    <td>${value.PostOffice[2].DeliveryStatus}</td>
    <td>${value.PostOffice[2].Circle}</td>
    <td>${value.PostOffice[2].District}</td>
    <td>${value.PostOffice[2].Division}</td>
    <td>${value.PostOffice[2].Region}</td>
    <td>${value.PostOffice[2].Block}</td>
    <td>${value.PostOffice[2].State}</td>
    <td>${value.PostOffice[2].Country}</td>
    <td>${value.PostOffice[2].Pincode}</td>
  </tr>
  <tr>
    <td>${value.PostOffice[3].Name}</td>
    <td>${value.PostOffice[3].Description}</td>
    <td>${value.PostOffice[3].BranchType}</td>
    <td>${value.PostOffice[3].DeliveryStatus}</td>
    <td>${value.PostOffice[3].Circle}</td>
    <td>${value.PostOffice[3].District}</td>
    <td>${value.PostOffice[3].Division}</td>
    <td>${value.PostOffice[3].Region}</td>
    <td>${value.PostOffice[3].Block}</td>
    <td>${value.PostOffice[3].State}</td>
    <td>${value.PostOffice[3].Country}</td>
    <td>${value.PostOffice[3].Pincode}</td>
  </tr>
  </table>
  `
});
document.getElementById("res").innerHTML=tab;
